

1.   Name : Emon Rifat Hasan 1832901 
2.   Name : Hibo Suleiman Amen 1825120
3.   Name : Amnah Salah Majzob Abdelmaged 1824962



In [27]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

In [28]:
data = pd.read_csv("/content/heart.csv")
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  outcome  oldpeak  \
0     63    1   3       145   233    1        0      150        0      2.3   
1     37    1   2       130   250    0        1      187        0      3.5   
2     41    0   1       130   204    0        0      172        0      1.4   
3     56    1   1       120   236    0        1      178        0      0.8   
4     57    0   0       120   354    0        1      163        1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...      ...      ...   
298   57    0   0       140   241    0        1      123        1      0.2   
299   45    1   3       110   264    0        1      132        0      1.2   
300   68    1   0       144   193    1        1      141        0      3.4   
301   57    1   0       130   131    0        1      115        1      1.2   
302   57    0   1       130   236    0        0      174        0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [53]:
X = np.array(data.drop(['thal'], 1))
y = np.array(data['thal'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [54]:
from sklearn.feature_selection import VarianceThreshold

selection = VarianceThreshold(threshold=(0.1))    
X = selection.fit_transform(X)
X.shape

(303, 13)

In [55]:
# Data splitting
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, stratify=y, test_size=0.2, random_state=42
)

In [56]:
X_train.shape, X_test.shape

((242, 13), (61, 13))

In [57]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import f1_score

# K nearest neighbors

In [58]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(3) 
knn.fit(X_train, y_train) 

# Make predictions
y_train_pred = knn.predict(X_train)
y_test_pred = knn.predict(X_test)

# Training set performance
knn_train_accuracy = accuracy_score(y_train, y_train_pred)*100 
knn_train_mcc = matthews_corrcoef(y_train, y_train_pred)*100 
knn_train_f1 = f1_score(y_train, y_train_pred, average='weighted')*100 

# Test set performance
knn_test_accuracy = accuracy_score(y_test, y_test_pred)*100 
knn_test_mcc = matthews_corrcoef(y_test, y_test_pred)*100 
knn_test_f1 = f1_score(y_test, y_test_pred, average='weighted')*100 

print('Model performance for Training set')
print('- Accuracy: %s' % knn_train_accuracy)
print('- MCC: %s' % knn_train_mcc)
print('- F1 score: %s' % knn_train_f1)
print('----------------------------------')
print('Model performance for Test set')
print('- Accuracy: %s' % knn_test_accuracy)
print('- MCC: %s' % knn_test_mcc)
print('- F1 score: %s' % knn_test_f1)

Model performance for Training set
- Accuracy: 76.03305785123968
- MCC: 55.81019406256292
- F1 score: 75.92379327913498
----------------------------------
Model performance for Test set
- Accuracy: 55.73770491803278
- MCC: 18.47549173297337
- F1 score: 55.36968885915022


In [59]:
print(confusion_matrix(y_train, y_train_pred))

[[  1   0   1   0]
 [  0   6   6   2]
 [  2   4 109  18]
 [  0   2  23  68]]


# SVM

In [60]:
from sklearn.svm import SVC

svm_rbf = SVC(gamma=2, C=1)
svm_rbf.fit(X_train, y_train)

# Make predictions
y_train_pred = svm_rbf.predict(X_train)
y_test_pred = svm_rbf.predict(X_test)

# Training set performance
svm_rbf_train_accuracy = accuracy_score(y_train, y_train_pred)*100
svm_rbf_train_mcc = matthews_corrcoef(y_train, y_train_pred)*100 
svm_rbf_train_f1 = f1_score(y_train, y_train_pred, average='weighted')*100 

# Test set performance
svm_rbf_test_accuracy = accuracy_score(y_test, y_test_pred)*100 
svm_rbf_test_mcc = matthews_corrcoef(y_test, y_test_pred)*100 
svm_rbf_test_f1 = f1_score(y_test, y_test_pred, average='weighted')*100 
print('Model performance for Training set')
print('- Accuracy: %s' % svm_rbf_train_accuracy)
print('- MCC: %s' % svm_rbf_train_mcc)
print('- F1 score: %s' % svm_rbf_train_f1)
print('----------------------------------')
print('Model performance for Test set')
print('- Accuracy: %s' % svm_rbf_test_accuracy)
print('- MCC: %s' % svm_rbf_test_mcc)
print('- F1 score: %s' % svm_rbf_test_f1)

Model performance for Training set
- Accuracy: 100.0
- MCC: 100.0
- F1 score: 100.0
----------------------------------
Model performance for Test set
- Accuracy: 54.09836065573771
- MCC: 0.0
- F1 score: 37.98395535402861


In [61]:
print(confusion_matrix(y_train, y_train_pred))

[[  2   0   0   0]
 [  0  14   0   0]
 [  0   0 133   0]
 [  0   0   0  93]]


# Hybrid Model 

Here We Combine KNN & SVM model


In [62]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

In [63]:
estimator_list = [
    ('knn',knn),
    ('svm_rbf',svm_rbf) ]

In [64]:
# Build stack model
stack_model = StackingClassifier(
    estimators=estimator_list, final_estimator=LogisticRegression()
)

In [65]:
# Train stacked model
stack_model.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  UserWarning,


StackingClassifier(estimators=[('knn', KNeighborsClassifier(n_neighbors=3)),
                               ('svm_rbf', SVC(C=1, gamma=2))],
                   final_estimator=LogisticRegression())

In [66]:
# Make predictions
y_train_pred = stack_model.predict(X_train)
y_test_pred = stack_model.predict(X_test)

In [67]:
# Training set model performance
stack_model_train_accuracy = accuracy_score(y_train, y_train_pred)*100 
stack_model_train_mcc = matthews_corrcoef(y_train, y_train_pred)*100 
stack_model_train_f1 = f1_score(y_train, y_train_pred, average='weighted')*100 

In [68]:
# Test set model performance
stack_model_test_accuracy = accuracy_score(y_test, y_test_pred)*100 
stack_model_test_mcc = matthews_corrcoef(y_test, y_test_pred)*100 
stack_model_test_f1 = f1_score(y_test, y_test_pred, average='weighted')*100 

In [69]:
print('Model performance for Training set')
print('- Accuracy: %s' % stack_model_train_accuracy)
print('- MCC: %s' % stack_model_train_mcc)
print('- F1 score: %s' % stack_model_train_f1)
print('')
print('Model performance for Test set')
print('- Accuracy: %s' % stack_model_test_accuracy)
print('- MCC: %s' % stack_model_test_mcc)
print('- F1 score: %s' % stack_model_test_f1)

Model performance for Training set
- Accuracy: 69.00826446280992
- MCC: 44.04388577074535
- F1 score: 63.353220206367055

Model performance for Test set
- Accuracy: 57.377049180327866
- MCC: 14.690718258463603
- F1 score: 50.10958183571491


In [70]:
print(confusion_matrix(y_train, y_train_pred))

[[  0   0   2   0]
 [  0   0  11   3]
 [  0   0 133   0]
 [  0   0  59  34]]


As we can see, the Accuracy and The confusion matrix gets better after we combine these two models.